default_stages: [pre-commit, pre-push]

exclude: ^build/

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        args: [--style=file]

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        language: system
        files: \.(cpp|c|h|hpp)$

  - repo: local
    hooks:
      - id: check-coverage
        name: Check Test Coverage
        entry: bash .hooks/check_coverage.sh
        language: system
        pass_filenames: false
