name: CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make g++ clang-format clang-tidy lcov gcovr

    - name: Setup CppUTest
      run: |
        git clone https://github.com/cpputest/cpputest.git
        cd cpputest
        cmake -S . -B build
        cmake --build build
        sudo make -C build install
        cd ..

    - name: Configure project with CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug \
                -DCMAKE_C_FLAGS="--coverage -O0 -g" \
                -DCMAKE_CXX_FLAGS="--coverage -O0 -g"

    - name: Build the project
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure -j1

    - name: Generate coverage (gcovr + lcov)
      run: |
          mkdir -p build/coverage
          echo "==== GCOVR ===="
          gcovr --root . --object-directory build --exclude 'test/' --sort-uncovered
          echo "==== LCOV (src only ) ===="
          lcov --capture --directory build/src --output-file build/coverage/coverage.info
          genhtml build/coverage/coverage.info --output-directory build/coverage/html

    - name: Upload HTML coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: build/coverage/html
        retention-days: 7
